import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import Container from "@/components/container/container";
import MainNav from "@/components/navbar/main-nav";

const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
     
        
      
        <main className="">
        {children}
        </main>
        <footer>
        <Footer/>
        </footer>
      
        </body>
    </html>
  );
}
